language: cpp

sudo: required
cache: ccache

if: tag IS blank

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: clang
      env: TARGET=linux64 USE_QT=qt5 DIST=bionic
      
    - os: linux
      dist: bionic
      compiler: gcc
      env: TARGET=linux64 USE_QT=qt5 DIST=bionic
      
    - os: linux
      dist: bionic
      env: TARGET=linux64 USE_QT=qt4
      
    - os: linux
      dist: bionic
      env: TARGET=linux64 USE_GTK=gtk3
      
    - os: linux
      dist: bionic
      env: TARGET=linux64 USE_GTK=gtk2
      
    - os: linux
      dist: bionic
      env: TARGET=linux64 USE_DAEMON=jsonrpc
      
    - os: osx
      osx_image: xcode12.3
      env: TARGET=macos64 macOS=11.1
      
    - os: linux
      dist: focal
      env: TARGET=windows32
      
    - os: linux
      dist: focal
      env: TARGET=windows64

install:
  - ./tests/travis-ci/install-build-depends.sh

script:
  - ./tests/travis-ci/build-and-test.sh
